### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by chris-est** [WeAreFairphone/android_device_fairphone_FP5#2]
Hello, thank your for providing a FP5 repo for LineageOS. I have a few questions about the status of this repo:

- Any instructions on how to build this?
- Which FP5 peripherals are currently supported (or not supported) by this build?
- Has this already been submitted to LineageOS (so it can become an 'official' build like the FP3 and FP4)?

Greetings and happy coding 📱

**Comment by arwarw** [comment]
I just got things to work with the usual FP4 build sequence at https://wiki.lineageos.org/devices/FP4/build/

Before the `repo sync` step, create a file `.repo/local_manifests/FP5.xml` with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="WeAreFairphone/android_device_fairphone_FP5" path="device/fairphone/FP5" remote="github" revision="lineage-21" />
  <project name="mikeNG/proprietary_vendor_fairphone_FP5" path="vendor/fairphone/FP5" remote="github" revision="lineage-21" />
  <project name="WeAreFairphone/android_kernel_fairphone_qcm6490" path="kernel/fairphone/qcm6490" remote="github" revision="lineage-21" />
  <project path="kernel/fairphone/sm7225" remote="github" name="LineageOS/android_kernel_fairphone_sm7225" revision="lineage-21" />
</manifest>
```

The output directory won't contain a recovery.img, that is fine. Just `adb sideload` the lineage*-FP5.zip, this will also install the recovery (different from FP4).

However, I didn't test anything in depth. It boots, looks fine so far, but I'll have to take a deeper look in the following days.

**Comment by chris-est** [comment]
Thank you for sharing your build info.
I should have updated this a while ago as there has been some movement towards a LineageOS FP5 build, see the current status [here](https://xdaforums.com/t/lineageos-for-fp5.4634848/) and unofficial releases are published [here](https://gitlab.com/awesome-fp5).

Two questions about your build:
1) There are 2x kernels in your xml file, do you need both for your build?
2) What recovery did you use to flash this? I had to flash /e/OS or iodéOS first to sideload my image from their recovery. I tried using the official Fairphone recovery and TWRP but both would not flash my image.

**Comment by arwarw** [comment]
0. I've seen those unofficial releases but didn't find a buildinfo for them, and wanted to try building it myself. Since things might need debugging later on, having a working build for myself is useful.

1. Good question about the second kernel, I've gotten the XML from [your 'current status' thread](https://xdaforums.com/t/lineageos-for-fp5.4634848/page-2#post-89213871) and changed it a little. I'll try leaving out the last line, that looks like the FP4 kernel.

2. I had e/os on the phone prior to trying this, so I've used the e/os recovery.

**Comment by chris-est** [comment]
I did not find any detailed build information for the already released builds (/e/ and iode) either :-(

We try to release an unofficial build soon including our how to build.
And maybe someday we will get an official build for the FP5 🤞

Closing this now as all the relevant information on how to build are here.

**Comment by arwarw** [comment]
Just tried without the sm7225 kernel and as expected, everything still works.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="WeAreFairphone/android_device_fairphone_FP5" path="device/fairphone/FP5" remote="github" revision="lineage-21" />
  <project name="mikeNG/proprietary_vendor_fairphone_FP5" path="vendor/fairphone/FP5" remote="github" revision="lineage-21" />
  <project name="WeAreFairphone/android_kernel_fairphone_qcm6490" path="kernel/fairphone/qcm6490" remote="github" revision="lineage-21" />
</manifest>
```
